knp_paginator:
  page_range: 5 # nombre de liens affichés dans le menu de pagination
  default_options:
    page_name: page # nom du paramètre de page dans l'URL
    sort_field_name: sort # nom du paramètre de tri
    sort_direction_name: direction # nom du paramètre de direction du tri
    distinct: true # assure des résultats distincts (utile avec GROUP BY)
    filter_field_name: filterField # nom du paramètre de filtrage
    filter_value_name: filterValue # nom de la valeur de filtre
  template:
    pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig' #template de pagination
    sortable: '@KnpPaginator/Pagination/bootstrap_v5_bi_sortable_link.html.twig' #template des liens de tri
    filtration: '@KnpPaginator/Pagination/bootstrap_v5_filtration.html.twig' #template des filtres